name: Build DNSCloak IPA

on:
  workflow_dispatch:

jobs:
  build-project:
    runs-on: macos-latest # Menggunakan macOS 13 yang versi Xcode-nya lebih bersahabat dengan proyek lama

    steps:
    - name: Ambil Source Code
      uses: actions/checkout@v4

    - name: Setup Node.js (Versi Aman untuk Cordova Lama)
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Setup Golang (Wajib untuk kompilasi Core TLS)
      uses: actions/setup-go@v5
      with:
        go-version: '1.18'

    - name: Install Dependensi npm
      run: |
        npm install
        npm install --only=dev

    - name: Build Framework & Persiapan Folder Cordova
      run: |
        npm run build

    - name: Kompilasi Proyek Xcode (Unsigned)
      run: |
        xcodebuild -workspace platforms/ios/DNSCryptApp.xcworkspace \
                   -scheme DNSCryptApp \
                   -configuration Release \
                   -sdk iphoneos \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_REQUIRED=NO \
                   CONFIGURATION_BUILD_DIR=${{ github.workspace }}/build \
                   clean build

    - name: Bungkus Menjadi File IPA
      run: |
        mkdir -p Payload
        cp -r ${{ github.workspace }}/build/DNSCryptApp.app Payload/
        zip -r DNSCloak.ipa Payload

    - name: Upload Hasil Jadi .IPA
      uses: actions/upload-artifact@v4
      with:
        name: DNSCloak-Free-Version
        path: DNSCloak.ipa
